// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqolckdpbhuknvrynces.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb2xja2RwYmh1a252cnluY2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDE3NjEsImV4cCI6MjA1MzQxNzc2MX0.X3iAWGusnQrNhSlG_zzjt5Oq74Ev9ulntdAK4f7hkoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);