// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auehrwmyvseotzulpcij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1ZWhyd215dnNlb3R6dWxwY2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NDgzODQsImV4cCI6MjA1MzQyNDM4NH0.fOuAjHPV9Rro0bNcrEIp9GenN8h5-mlZBlnOWoib7ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);